version: '2'
services:
    web:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 3000:80
        depends_on:
            - php
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./php:/app
            - /app/vendor
        depends_on:
            - postgres
        environment:
            DATABASE_URL: "postgres://${PSQL_USR}@postgres/${PSQL_DB}"
    postgres:
        build:
            context: ./psql
            dockerfile: Dockerfile
        # image: postgres:9.6.2-alpine
        environment:
            POSTGRES_USER: ${PSQL_USR}
            POSTGRES_DB: ${PSQL_DB}


env_file:
  - path: ./.env
    required: true